name: CI Build and Release (Android APK)

on:
  push:
    branches: [ main, ci-issues ]

permissions:
  contents: write

env:
  NODE_VERSION: '20'
  WORKING_DIR: apps/native

jobs:
  android-apk:
    name: Android APK (debug)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Install deps (root)
        run: pnpm install --frozen-lockfile
      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Prebuild Android (no install)
        working-directory: ${{ env.WORKING_DIR }}
        run: npx --yes expo prebuild --platform android --non-interactive --no-install
      - name: Build debug APK
        working-directory: ${{ env.WORKING_DIR }}/android
        run: ./gradlew assembleDebug | cat
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: ${{ env.WORKING_DIR }}/android/app/build/outputs/apk/debug/app-debug.apk

  create-release:
    name: GitHub Release (attach APK)
    runs-on: ubuntu-latest
    needs: [android-apk]
    steps:
      - name: Download Android artifact
        uses: actions/download-artifact@v4
        with:
          name: android-debug-apk
          path: ./dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ci-${{ github.sha }}
          release_name: CI Build ${{ github.sha }}
          draft: false
          prerelease: true
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/app-debug.apk
          asset_name: app-android-debug-${{ github.sha }}.apk
          asset_content_type: application/vnd.android.package-archive

  # Optional: Signed release builds (requires secrets)
  # (Optional) Add a signed release job later when keystore secrets are ready.


